---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_port: '22'
    - ENVIRONMENT: "production"
    - TYPEORM_CONNECTION: "${TYPEORM_CONNECTION}"
    - TYPEORM_ENTITIES: "${TYPEORM_ENTITIES}"
    - TYPEORM_HOST: "${TYPEORM_HOST}"
    - TYPEORM_PORT: "${TYPEORM_PORT}"
    - TYPEORM_USERNAME: "${TYPEORM_USERNAME}"
    - TYPEORM_PASSWORD: "${TYPEORM_PASSWORD}"
    - TYPEORM_DATABASE: "${TYPEORM_DATABASE}"

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 60

    - name: "install python for Ansible"
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - setup:

  roles:
    - configure-server