- name: Copy backend files
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Start PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    pm2 start npm --name backend -- start